kind: pipeline
name: default
type: docker

steps:
- name: build-java
  image: maven:3-jdk-11
  commands:
  - cd stampli-backend
  - mvn compile

- name: test-java
  image: maven:3-jdk-11
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
  - cd stampli-backend
  - mvn verify -DtestNoDB -Dtest.mysql.host=testDB

- name: deploy-copy
  image: appleboy/drone-scp
  settings:
    host: artur.at.hsp.sh
    username: psuwala
    key:
      from_secret: ssh_key
    port: 22
    rm: true
    target: /etc/nixos/docker/stampli/target/
    source: ./*
- name: deploy-start-compose
  image: appleboy/drone-ssh
  settings:
    host: artur.at.hsp.sh
    username: psuwala
    key:
      from_secret: ssh_key
    port: 22
    script:
      - cd /etc/nixos/docker/stampli/target/
      - docker-compose build
      - docker-compose down
      - docker-compose up --detach --remove-orphans

services:
  - name: testDB
    image: mariadb:10.5.9
    environment:
      MYSQL_DATABASE: baza
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
