kind: pipeline
name: default

environment:
  DEPLOY_HOST: artur.at.hsp.sh
  DEPLOY_USERNAME: psuwala
  DEPLOY_FOLDER: /etc/nixos/docker/stampli

steps:
- name: build-java
  image: maven:3-jdk-11
  commands:
  - cd stampli-backend
  - mvn install
- name: deploy-copy
  image: appleboy/drone-scp
  settings:
    host: $DEPLOY_HOST
    username: $DEPLOY_USERNAME
    key:
      from_secret: ssh_key
    port: 22
    target: $DEPLOY_FOLDER
    source: /*
- name: deploy-start-compose
  image: appleboy/drone-ssh
  settings:
    host: $DEPLOY_HOST
    username: $DEPLOY_USERNAME
    key:
      from_secret: ssh_key
    port: 22
    script:
      - cd ${DEPLOY_FOLDER}
      - docker-compose build
      - docker-compose up --detach
