kind: pipeline
name: default

steps:
- name: build-java
  image: maven:3-jdk-11
  commands:
  - cd stampli-backend
  - mvn install
- name: deploy-copy
  image: appleboy/drone-scp
  settings:
    host: artur.at.hsp.sh
    username: psuwala
    key:
      from_secret: ssh_key
    port: 22
    target: /etc/nixos/docker/stampli
    source: ./*
- name: deploy-start-compose
  image: appleboy/drone-ssh
  settings:
    host: artur.at.hsp.sh
    username: psuwala
    key:
      from_secret: ssh_key
    port: 22
    script:
      - cd /etc/nixos/docker/stampli
      - docker-compose build
      - docker-compose up --detach
