kind: pipeline
name: default
type: docker

steps:

- name: java-verify
  image: maven:3-jdk-17
  commands:
  - cd stamply-backend
  - mvn verify -DnoTestDB -Dtest.mysql.host=db -Dtest.rabbitmq.host=queue

- name: node-test
  image: node:17.8.0
  commands:
  - cd stamply-frontend
  - npm install
  - npx tsc
  - npm test

- name: deploy-copy
  image: appleboy/drone-scp
  settings:
    host: artur.at.hsp.sh
    username: psuwala
    key:
      from_secret: ssh_key
    port: 22
    rm: true
    target: /etc/nixos/docker/stampli/target/
    source: ./*

- name: deploy-start-compose
  image: appleboy/drone-ssh
  settings:
    host: artur.at.hsp.sh
    username: psuwala
    key:
      from_secret: ssh_key
    port: 22
    script:
      - cd /etc/nixos/docker/stampli/target/
      - docker-compose build
      - docker-compose down
      - docker-compose -f docker-compose.yml -f deployment/production.yml up --detach 

services:
  - name: db
    image: mariadb:10.5.9
    environment:
      MYSQL_DATABASE: baza
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  - name: queue
    image: rabbitmq:3.8
