version: "3.3"
services:
  server1:
    build: './stampli-backend'
  server2:
    build: './stampli-backend'
  nginx:
    build: './nginx'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stampli.rule=Host(`stampli.at.hsp.sh`)"
      - "traefik.http.routers.stampli.entrypoints=websecure"
      - "traefik.http.routers.stampi.tls=true"
      - "traefik.http.routers.stampli.tls.certresolver=le"

