version: "3.3"
services:
  server1:
    build: './stampli-backend'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: baza
    networks:
      - stampli

  front:
    build: './stampli-frontend'
    networks:
      - stampli

  db:
    image: mariadb:10.5.9
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSOWRD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: baza
    networks:
      - stampli

  nginx:
    build: './nginx'
    networks:
      - stampli

networks:
  stampli:
    internal: true
