version: "3.3"
services:
  server1:
    build: './stamply-backend'
    environment:
      mysql.username: root
      mysql.password: password
      mysql.host: stampli_db
      mysql.port: 3306
      mysql.db: baza
    networks:
      - stamply

  front:
    build: './stamply-frontend'
    networks:
      - stamply

  stampli_db:
    image: mariadb:10.5.9
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSOWRD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: baza
    networks:
      - stamply

  nginx:
    build: './nginx'
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - stamply

networks:
  stamply:
    internal: false
