version: "3.3"
services:
  server1:
    build: './stampli-backend'
    ports: # for local only
     - 1995:1995
    environment:
      
  front:
    build: './stampli-frontend'
  nginx:
    build: './nginx'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stampli.rule=Host(`stampli.at.hsp.sh`)"
      - "traefik.http.routers.stampli.entrypoints=websecure"
      - "traefik.http.routers.stampli.tls=true"
      - "traefik.http.routers.stampli.tls.certresolver=le"
networks:
  default:
    external:
      name: common-network
