version: "3.3"
services:
  server1:
    ports:
      - 1995:1995
    volumes:
      - type: bind
        source: ./stampli-backend/target/stampli-output/
        target: /usr/local/stampli/stampli/
  db:
    ports:
      - 3306:3306
  nginx:
    build: './nginx'
    networks:
      - stampli
    ports:
      - 80:80
  front:
    volumes:
      - type: bind
        source: ./stampli-frontend
        target: /node
    environment:
      BASE_URL: 'http://localhost'
      OAUTH__GOOGLE__CLIENT_ID: '155167860801-q5hj0hi3hhdrgton1aoplfd026tgfch7.apps.googleusercontent.com'
