version: "3.3"
services:
  front:
    environment:
      BASE_URL: 'https://stampli.at.hsp.sh'
      OAUTH__GOOGLE__CLIENT_ID: '155167860801-q5hj0hi3hhdrgton1aoplfd026tgfch7.apps.googleusercontent.com'
  nginx:
    build: './nginx'
    labels:
      - "traefik.docker.network=outside"
      - "traefik.enable=true"
      - "traefik.http.routers.stampli.rule=Host(`stampli.at.hsp.sh`)"
      - "traefik.http.routers.stampli.entrypoints=websecure"
      - "traefik.http.routers.stampli.tls=true"
      - "traefik.http.routers.stampli.tls.certresolver=le"
    networks:
      - outside
      - stampli
networks:
  outside:
    external:
      name: common-network
  stampli:
    internal: true
