@startuml

hide methods

entity Business {
businessId : Integer
}

entity BusinessOffer {
offerId : Integer
businessId : Integer
image : Blob
}

entity RedeemedBy {
offerId : Integer
userId : Integer
}

Business -> BusinessOffer
BusinessOffer -> RedeemedBy

@enduml