name: master

on:
  push:
    branches:
      - "master"

env:
  DOCKER_USER: psuwala
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: ksidelta
  KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
  DISCORD_API_KEY: ${{ secrets.DISCORD_API_KEY }}
  DISCORD_GROUP: ${{ secrets.DISCORD_GROUP }}
  K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE }}

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build with Maven
        run: cd ./stamply-backend && mvn verify 
  node:
    runs-on: ubuntu-latest--batch-mode --update-snapshots package
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17.8.0
        uses: actions/setup-node@v3
        with:
          node-version: 17.8.0
      - run: npm ci
      - run: npm run build
      - run: npm run test

